# Generated by Django 3.2.3 on 2021-05-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0003_alter_profession_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('addon', models.CharField(max_length=40)),
                ('img', models.CharField(max_length=100)),
            ],
        ),
    ]
